name: Build release

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          Add-Content $env:GITHUB_OUTPUT "sha_short=$(git rev-parse --short HEAD)"

      - name: Append git revision to project version
        run: |
          (Get-Content version.py) `
          -Replace '^__version__\s*=\s*"[^"]+', "`$0.${{steps.vars.outputs.sha_short}}" |`
          Out-File version.py

      # Ensure Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install project dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r requirements.txt

      - name: Install UPX
        run: |
          Invoke-WebRequest -Uri https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip -OutFile (Join-Path $env:Temp upx.zip)
          Expand-Archive -LiteralPath (Join-Path $env:Temp upx.zip) -DestinationPath $env:Temp
          Move-Item -Path (Join-Path $env:Temp upx-*) -Destination (Join-Path $env:Temp upx)
          Add-Content $env:GITHUB_PATH (Join-Path $env:Temp upx)

      - name: Install PyInstaller
        run: |
          python3 -m pip install pyinstaller

      - name: Create portable executable
        run: |
          pyinstaller build.spec

      - name: Create release folder
        run: |
          $FolderName = 'Twitch Drops Miner Unrestricted'
          New-Item $FolderName -ItemType Directory
          Copy-Item dist\*.exe $FolderName
          Copy-Item manual.txt $FolderName
          Compress-Archive -Path $FolderName -DestinationPath Twitch.Drops.Miner.Unrestricted.Windows.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Twitch.Drops.Miner.Unrestricted.Windows
          path: Twitch.Drops.Miner.Unrestricted.Windows.zip

  update_releases_page:
    name: Upload builds to Releases
    #NOTEif: github.event.pull_request.merged == true
    needs:
      - windows
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: semver
          increment: minor

      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date --rfc-3339=seconds)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Download build artifacts from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Read patch notes from file
        id: patch_notes
        uses: juliangruber/read-file-action@v1.1.7
        with:
          path: ./patch_notes.txt

      - name: Upload builds to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*/*
          body: |
            # ⚠️ Please help with translation as tracked in #2 (Indonesian) and channel points as tracked in #23 !

            ***
            **This is an automatically generated updated version of the application, that includes the latest master branch changes.**
            **This build should be stable, but if you encounter anything, please report any issues you find.**

            - Last build date: `${{ steps.vars.outputs.date_now }}`
            - Reference commit: ${{ github.sha }}
            
            ***
            ## Patch notes:
            ${{ steps.patch_notes.outputs.content }}

          name: ${{ steps.version.outputs.v-version }} - Updated tested build (${{ steps.vars.outputs.sha_short }})
          prerelease: false
          removeArtifacts: true
          tag: ${{ steps.version.outputs.v-version }}
